### ISSUE TITLE
This implementation of RK does not seem correct

### ISSUE THREAD

**Issue by masterpiga** [mccricardo/Rabin-Karp#1]
Hi there,
I stumbled on this page by chance. I am under the impression that this is not a correct implementation of RK. The core idea of RK is to use a "rolling" hash function to calculate the hash of each substring of the "haystack" string, so that every time you move forward by one position you are actually hashing only 1 character. This gives the whole algorithm a complexity if O(|haystack| + |needle|). In your implementation, you are calculating a new hash for every position in haystack. You are doing it |haystack| times, and each time the complexity is |needle|, so the overall worst case scenario complexity of the algorithm is still O(|haystack| \* |needle|), which is the same as with the naive string matching approach:

for i in range(0, len(haystack) - len(needle) + 1):
  if needle = haystack[i, i + len(needle)]:
    return True
return False

Please, let me know if you think that I am wrong.
Regards

**Comment by mccricardo** [comment]
Hi masterpiga,

First of all thank you for your comment.

You're absolutely right. This implementation was only an initial overview of the algorithm. The rolling hash has not yet been implemented. I will make this clear in the description.

Ricardo Castro

**Comment by mccricardo** [comment]
First  implementation of the rolling hash,
